### ISSUE TITLE
Create a `GalleryDetailFragment` that displays when an item in the gallery is selected.

### ISSUE THREAD

**Issue by Lionel1232** [IRTSA-SoftwareProject/IRTSA-App#25]
## Create a `GalleryDetailFragment` that displays when an item in the gallery is selected.

# Description:
Tapping on a gallery entry should bring up a new screen that has the following (minimum) functionality:
- Change the name of the scan
- Change the description of the scan.
- Display a larger version of the selected gallery image.
- (**Optional, and possibly a seperate issue**) Implement a button on the navbar for this fragment so the scan can be saved to the local device. Dependent on #24 

# Justification:
This feature is a critical part of the mobile app. This feature will allow the user of the application to view past scan, and edit its associated data. Without this feature, very limited information/ability to view a scan image would be present.

**Comment by Casper-P** [comment]
**Fragment has been created with the following functions:**
 - Displays image
 - Shows image name
 - Shows images description

**Functionality to be added:**
 - Delete
 - Rename
 - Export
